-- Add missing columns to profiles table to support Health Sync
-- Run this in Supabase SQL Editor

ALTER TABLE profiles 
  ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION DEFAULT 175.0,
  ADD COLUMN IF NOT EXISTS resting_heart_rate INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS ftp INTEGER DEFAULT 200,
  ADD COLUMN IF NOT EXISTS hrv INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS sleep_hours DOUBLE PRECISION DEFAULT 7.0,
  ADD COLUMN IF NOT EXISTS thermal_sensitivity INTEGER DEFAULT 3,
  ADD COLUMN IF NOT EXISTS health_history JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS last_health_sync TIMESTAMP WITH TIME ZONE;
